apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ["$(JENKINS_SECRET)", "$(JENKINS_NAME)"]
    - name: gcloud-builder
      image: google/cloud-sdk:latest
      command:
        - cat
      tty: true
